[package]
name = "day08"
version = "0.1.0"
edition = "2024"

[dependencies]
macros.workspace = true
rayon = { version = "1.11.0", optional = true }

[features]
default = []
rayon = ["dep:rayon"]

[lints.clippy]
nursery = "warn"
